#!/usr/bin/env bash
#print 10 times and at 4th and 8th different form the parent

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
