#!/usr/bin/env bash
#print diffrent 

count=0
while [ $count -le 20 ]
do
	case $count in
		4)
			echo $count
			echo "bad luck from china"
			;;
		9)
			echo $count
			echo "bad luck form Japan"
			;;
		17)
			echo $count
			echo "bad luck form Italy"
			;;
		*)
			echo $count
			;;
		esac
	((count++))
done
