#!/usr/bin/env bash
#print diffrent 

count=0
while [ $count -lt 20 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck from china"
    elif [ $count -eq 9 ]
    then
        echo "bad luck from japan"
    elif [ $count -eq 17 ]
    then
        echo "bad luck from Italy"
    else
        echo "$count"
    fi
    ((count++))
done
